name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O deploy roda toda vez que você der push na main

permissions:
  contents: write # Permissão para o robô escrever na branch gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código 🛎️
        uses: actions/checkout@v4

      - name: Instalar Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Dependências e Build 🏗️
        run: |
          npm install
          npm run build

      - name: Deploy para a branch gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # A pasta que o Vite gera
          branch: gh-pages # A branch que o GitHub Pages está lendo